### PR TITLE
Add draft for second pangeo post

### PR DESCRIPTION
**Pull request by mrocklin**
cc @rabernat @yuvipanda @jacobtomlinson @jhamman

### CODE REVIEW

**Comment by rabernat** [comment]
Matt, this looks great! How do you get so much done *and* find time to write about it elegantly.

**Comment by yuvipanda** [comment]
Awesome :) /cc @choldgraf @willingc @minrk (others doing z2jh work)

**Comment by rabernat** [comment]
Would you be open to cross-posting this with the Pangeo blog? It is a little sad at the moment, and it would be great to have some more meaty content up there (especially if any of the purse-string-holders happen to visit it). We can make it clear that you blog is the "primary" location for the post.

**Comment by mrocklin** [comment]
Happy to move it anywhere.  I'd also be very happy to have others
add/delete/modify content

**Comment by mrocklin** [comment]
Also, my objective here was just a progress report and brain dump.  This
isn't intended to be a big thing.  We should eventually write up a big
thing once everything works more smoothly.

**Comment by rabernat** [comment]
You brain dump is great. Very useful to have it written down. (The thing I was calling "sad" was the pangeo blog, not your excellent post, in case that was unclear.) I was not proposing moving this from your blog. I just want to duplicate it on the pangeo blog, with a link back to your original post.

**Comment by jhamman** [comment]
This looks great. Thanks @mrocklin for the writup. Cross posting seems like a good idea. I have been meaning to write a similar status update for the HPC deployments.

**Comment by jacobtomlinson** [comment]
Looks really good. 

I would perhaps suggest the myself and @mkjpryor-stfc are listed as separate contributors as we work for different organisations. There's also a typo in my name 😄.

cc @niallrobinson

**Comment by mrocklin** [comment]
Pushed updates.  Merging and posting live Monday morning.

**Pull request merged**
