### PR TITLE
credit models with dask

### PR DESCRIPTION
**Pull request by postelrich**

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks!  I plan to take a crack at this in a few hours.

**Comment by mrocklin** [comment]
I've submitted a PR to this PR here: https://github.com/postelrich/blog/pull/1

Also, is it possible to use Gephi to generate SVG images, such that people might be able to zoom around on their own?  If so, can we also generate them with a transparent background, such that they could be used both within white-backgrounded articles like this blog, and also slide presentations in the future?

**Comment by postelrich** [comment]
@mrocklin I added svg images but you might want to generate the actually webpage to check if the sizes are good.

**Comment by mrocklin** [comment]
Looking at the images it seems like the colors used for the edges don't
come out well against a white background.  They're not particularly visible.

**Comment by postelrich** [comment]
Can you post a screenshot?

**Comment by mrocklin** [comment]
It's visible from github: https://github.com/postelrich/blog/blob/ea6b3564e43d0b346d2cdde7ed9eac7a76b6ce93/images/credit_mo

**Comment by mrocklin** [comment]
Sorry, better link: https://github.com/postelrich/blog/blob/ea6b3564e43d0b346d2cdde7ed9eac7a76b6ce93/images/credit_models/graph_agg.svg

**Comment by postelrich** [comment]
@mrocklin too complicated to try to figure out how to change the colors on the edges.

**Comment by mrocklin** [comment]
Do you have a file that I can use to try to generate an image?  Happy to
download Gephi and play around.

**Pull request merged**
