### PR TITLE
Update analysis section

### PR DESCRIPTION
**Pull request by moody-marlin**

### CODE REVIEW

**Comment by mrocklin** [comment]
This looks good to me.  Should we say anything about how this is toy data and how uniformity might be affecting things?

**Comment by moody-marlin** [comment]
Yea, for sure; should I include that in the Analysis section or in the "Things we could have done better"?

**Comment by mrocklin** [comment]
Whatever makes more sense to you.  I think that you probably have a better understanding here than I do.

**Comment by mrocklin** [comment]
Also no huge rush on this.  I would probably publish early next week.

**Comment by moody-marlin** [comment]
Ok cool

**Comment by mrocklin** [comment]
Checking in on status here.

**Comment by mrocklin** [comment]
From a mathematical perspective is the content here defensible?  Are there other notes that we would like to add?

**Comment by moody-marlin** [comment]
Yea, it's defensible; I believe I was supposed to add a few additional comments about this being fake data.  Let me do that in a minute.

**Comment by moody-marlin** [comment]
I think most of my other comments / notes end up spiraling into out-of-scope territory, so I think this looks good.

**Comment by mrocklin** [comment]
OK cool.  Thanks for this.  Pushing it out tomorrow morning.

**Pull request merged**
